/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package libratech.dashboard;

import com.google.firebase.auth.FirebaseAuthException;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.filechooser.FileNameExtensionFilter;
import libratech.auth.login;
import libratech.auth.signup;
import static libratech.auth.signup.validateGmail;
import libratech.design.GlassPanePopup;
import libratech.design.ImageScaler;
import libratech.design.RoundedPanel;
import libratech.design.RoundedPanelBorderless;
import libratech.models.auth;
import libratech.models.pushValue;
import libratech.models.retrieve;
import libratech.util.firebaseInit;
import libratech.util.storage;

/**
 *
 * @author noemi
 */
public class add_user extends javax.swing.JPanel {

    private String localFilePath;
    private String remoteFilePath;
    ImageScaler scaler = new ImageScaler();
    private DatabaseReference databaseReference;
    private HashMap<String, Object> m;
    private pushValue v;
    private retrieve r;
    
    public add_user() {
        initComponents();
        this.databaseReference = FirebaseDatabase.getInstance().getReference();
        new firebaseInit().initFirebase();
        initFont();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fullnamelabel = new javax.swing.JLabel();
        idnolabel = new javax.swing.JLabel();
        cancellabel = new libratech.design.MyButtonborderless();
        addbooklabel = new libratech.design.MyButtonborderless();
        dateofbirthlabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        phonelabel = new javax.swing.JLabel();
        booktitle1 = new javax.swing.JTextField();
        addresslabel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        sexlabel = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        sex = new javax.swing.JTextField();
        idno = new javax.swing.JTextField();
        dateofbirth = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        coursegrade = new javax.swing.JTextField();
        coursegradelabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 791));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(58, 58, 58));
        jLabel2.setText("Add book");

        fullnamelabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fullnamelabel.setForeground(new java.awt.Color(51, 51, 51));
        fullnamelabel.setText("Full Name:");

        idnolabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idnolabel.setForeground(new java.awt.Color(51, 51, 51));
        idnolabel.setText("ID no:");

        cancellabel.setForeground(new java.awt.Color(224, 224, 224));
        cancellabel.setText("Cancel");
        cancellabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellabelActionPerformed(evt);
            }
        });

        addbooklabel.setForeground(new java.awt.Color(224, 224, 224));
        addbooklabel.setText("Add book");
        addbooklabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbooklabelActionPerformed(evt);
            }
        });

        dateofbirthlabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateofbirthlabel.setForeground(new java.awt.Color(51, 51, 51));
        dateofbirthlabel.setText("Date of birth:");

        emaillabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emaillabel.setForeground(new java.awt.Color(51, 51, 51));
        emaillabel.setText("Email:");

        phonelabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        phonelabel.setForeground(new java.awt.Color(51, 51, 51));
        phonelabel.setText("Phone:");

        booktitle1.setBackground(new java.awt.Color(250, 250, 250));
        booktitle1.setBorder(null);
        booktitle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booktitle1ActionPerformed(evt);
            }
        });
        booktitle1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                booktitle1KeyReleased(evt);
            }
        });

        addresslabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addresslabel.setForeground(new java.awt.Color(51, 51, 51));
        addresslabel.setText("Address:");

        email.setBackground(new java.awt.Color(250, 250, 250));
        email.setBorder(null);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        sexlabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sexlabel.setForeground(new java.awt.Color(51, 51, 51));
        sexlabel.setText("Sex:");

        fullname.setBackground(new java.awt.Color(250, 250, 250));
        fullname.setBorder(null);
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        fullname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fullnameKeyReleased(evt);
            }
        });

        sex.setBackground(new java.awt.Color(250, 250, 250));
        sex.setBorder(null);
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });
        sex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sexKeyReleased(evt);
            }
        });

        idno.setBackground(new java.awt.Color(250, 250, 250));
        idno.setBorder(null);
        idno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnoActionPerformed(evt);
            }
        });
        idno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idnoKeyReleased(evt);
            }
        });

        dateofbirth.setBackground(new java.awt.Color(250, 250, 250));
        dateofbirth.setBorder(null);
        dateofbirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateofbirthActionPerformed(evt);
            }
        });
        dateofbirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateofbirthKeyReleased(evt);
            }
        });

        phone.setBackground(new java.awt.Color(250, 250, 250));
        phone.setBorder(null);
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });

        address.setBackground(new java.awt.Color(250, 250, 250));
        address.setBorder(null);
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        coursegrade.setBackground(new java.awt.Color(250, 250, 250));
        coursegrade.setBorder(null);
        coursegrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursegradeActionPerformed(evt);
            }
        });
        coursegrade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coursegradeKeyReleased(evt);
            }
        });

        coursegradelabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        coursegradelabel.setForeground(new java.awt.Color(51, 51, 51));
        coursegradelabel.setText("Course/Grade:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(dateofbirthlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(337, 337, 337)
                                                    .addComponent(sexlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(332, 332, 332)))
                                            .addComponent(emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(phonelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(idno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                                                        .addComponent(dateofbirth, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addComponent(idnolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(coursegrade)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(coursegradelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(0, 0, Short.MAX_VALUE)))))
                                        .addGap(820, 820, 820))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(617, 617, 617)
                                        .addComponent(cancellabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(addbooklabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(booktitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(fullnamelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idnolabel)
                    .addComponent(coursegradelabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(booktitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                        .addContainerGap(404, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coursegrade, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateofbirthlabel)
                            .addComponent(sexlabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(emaillabel)
                        .addGap(18, 18, 18)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addresslabel)
                        .addGap(18, 18, 18)
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phonelabel)
                        .addGap(18, 18, 18)
                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancellabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addbooklabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void booktitle1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_booktitle1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_booktitle1KeyReleased

    private void booktitle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booktitle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booktitle1ActionPerformed

    private void addbooklabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbooklabelActionPerformed
        // TODO add your handling code here:
        String full_name = fullname.getText();
        String id_no = idno.getText();
        String course_grade = coursegrade.getText();
        String date_of_birth = dateofbirth.getText();
        String sex1 = sex.getText();
        String email1 = email.getText();
        String address1 = address.getText();
        String phone1= phone.getText();
        

        if (full_name.equals("") || id_no.equals("") || course_grade.equals("") || date_of_birth.equals("") || sex1.equals("") || email1.equals("") || address1.equals("") || phone1.equals("")) {
            JOptionPane.showMessageDialog(null, "Error: Field is empty", "Error", ERROR_MESSAGE);
        } else {
//            String getnow = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime());
//            String key = databaseReference.push().getKey();
//            v = new pushValue(databaseReference.push().getKey());
//            m = new HashMap<>();
//            m.put("booktitle", book_title);
//            m.put("bookauthor", book_author);
//            m.put("publisher", publ);
//            m.put("dewey", dew);
//            m.put("genre", genr);
//            m.put("date", date1);
//            m.put("quantity", quan);
//            m.put("shelf", shelff);
//            m.put("deck", deckk);
//            m.put("key", key);
//            m.put("status", "Available");
//            m.put("timestamp", getnow);
//            m.put("cover", downloadUrl);
//            v.pushData("books/inshelf", m);
//            JOptionPane.showMessageDialog(null, "Add book", "Book added Successfully", INFORMATION_MESSAGE);
            GlassPanePopup.closePopupLast();
        }
    }//GEN-LAST:event_addbooklabelActionPerformed

    private void cancellabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellabelActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_cancellabelActionPerformed

    private void sexKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sexKeyReleased
        // TODO add your handling code here:
        String text = sex.getText();
        String str = "";
        // Capitalize the first letter of the text
        if (text.length() > 0) {
            text = Character.toUpperCase(text.charAt(0)) + text.substring(1);
            sex.setText(text);
        }

        if (text.length() > 24) {
            str = text.substring(0, 24);
            sex.setText("");
        }

        if (text.length() == 0) {
            sex.setText(str);
            str = "";
        }
    }//GEN-LAST:event_sexKeyReleased

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void fullnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullnameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameKeyReleased

    private void idnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnoActionPerformed

    private void idnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idnoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_idnoKeyReleased

    private void dateofbirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateofbirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateofbirthActionPerformed

    private void dateofbirthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateofbirthKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dateofbirthKeyReleased

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void coursegradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursegradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coursegradeActionPerformed

    private void coursegradeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coursegradeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_coursegradeKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private libratech.design.MyButtonborderless addbooklabel;
    private javax.swing.JTextField address;
    private javax.swing.JLabel addresslabel;
    private javax.swing.JTextField booktitle1;
    private libratech.design.MyButtonborderless cancellabel;
    private javax.swing.JTextField coursegrade;
    private javax.swing.JLabel coursegradelabel;
    private javax.swing.JTextField dateofbirth;
    private javax.swing.JLabel dateofbirthlabel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel fullnamelabel;
    private javax.swing.JTextField idno;
    private javax.swing.JLabel idnolabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phonelabel;
    private javax.swing.JTextField sex;
    private javax.swing.JLabel sexlabel;
    // End of variables declaration//GEN-END:variables
    public void initFont() {
        fullnamelabel.setFont(new Font("Poppins Regular", Font.BOLD, 12));
        fullname.setFont(new Font("Poppins Regular", Font.PLAIN, 12));
        idnolabel.setFont(new Font("Poppins Regular", Font.BOLD, 12));
        idno.setFont(new Font("Poppins Regular", Font.PLAIN, 12));
        coursegradelabel.setFont(new Font("Poppins Regular", Font.BOLD, 12));
        coursegrade.setFont(new Font("Poppins Regular", Font.PLAIN, 12));
        dateofbirthlabel.setFont(new Font("Poppins Regular", Font.BOLD, 12));
        dateofbirth.setFont(new Font("Poppins Regular", Font.PLAIN, 12));
        sexlabel.setFont(new Font("Poppins Regular", Font.BOLD, 12));
        sex.setFont(new Font("Poppins Regular", Font.PLAIN, 12));
        emaillabel.setFont(new Font("Poppins Regular", Font.BOLD, 12));
        email.setFont(new Font("Poppins Regular", Font.PLAIN, 12));
        addresslabel.setFont(new Font("Poppins Regular", Font.BOLD, 12));
        address.setFont(new Font("Poppins Regular", Font.PLAIN, 12));
        phonelabel.setFont(new Font("Poppins Regular", Font.BOLD, 12));
        phone.setFont(new Font("Poppins Regular", Font.PLAIN, 12));

        

    }
}
