/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package libratech.dashboard;

import java.awt.Color;
import java.awt.Font;
import libratech.design.RoundedPanel;

/**
 *
 * @author Lenovo
 */
public class category_confimation_dialog extends javax.swing.JPanel {

    /**
     * Creates new form category_confimation_dialog
     */
    public category_confimation_dialog() {
        initComponents();
        initFont();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        categoryconfirmationlabel = new javax.swing.JLabel();
        txt = new javax.swing.JTextPane();
        confirmlabel = new libratech.design.MyButtonborderless();
        cancellabel = new libratech.design.MyButtonborder();

        jTextField1.setText("jTextField1");

        categoryconfirmationlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        categoryconfirmationlabel.setText("Category Confirmation");

        txt.setText("Are you sure you want to add this category?\n\n\tThis action cannot be undone.");
        txt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        confirmlabel.setForeground(new java.awt.Color(224, 224, 224));
        confirmlabel.setText("Confirm");

        cancellabel.setForeground(new java.awt.Color(23, 23, 23));
        cancellabel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryconfirmationlabel))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancellabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(categoryconfirmationlabel)
                .addGap(18, 18, 18)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancellabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private libratech.design.MyButtonborder cancellabel;
    private javax.swing.JLabel categoryconfirmationlabel;
    private libratech.design.MyButtonborderless confirmlabel;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane txt;
    // End of variables declaration//GEN-END:variables
public void initFont() {
        categoryconfirmationlabel.setFont(new Font("Poppins Regular", Font.BOLD, 20));
        confirmlabel.setFont(new Font("Poppins Regular", Font.BOLD, 20));
        cancellabel.setFont(new Font("Poppins Regular", Font.BOLD, 20));
        
    }
}

