/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package libratech.dashboard;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import javax.swing.SwingUtilities;
import libratech.auth.splash;
import libratech.design.GlassPanePopup;

/**
 *
 * @author Carocoy
 */
public class profile_dialog extends javax.swing.JPanel {

    /**
     * Creates new form profile_dialog
     */
    public profile_dialog() {
        initComponents();
        setOpaque(false);
        txt.setBackground(new Color(0, 0, 0, 0));
        txt.setOpaque(false);
        txt.setEditable(false);
        initFont();
    }
    @Override
    protected void paintComponent(Graphics graphics) {
        Graphics2D g2 = (Graphics2D) graphics.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        g2.dispose();
        super.paintComponent(graphics);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        savechangeslabel = new javax.swing.JLabel();
        txt = new javax.swing.JTextPane();
        saveprofile = new libratech.design.MyButtonborderless();
        cancel = new libratech.design.MyButtonborder();

        savechangeslabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        savechangeslabel.setText("Save Changes");

        txt.setText("Are you sure you want to change your profile?\n\nChanging your profile will update your personal information and settings. This action cannot be undone.");
        txt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        saveprofile.setForeground(new java.awt.Color(224, 224, 224));
        saveprofile.setText("Change Profile");
        saveprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveprofileActionPerformed(evt);
            }
        });

        cancel.setForeground(new java.awt.Color(23, 23, 23));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveprofile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savechangeslabel))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(savechangeslabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>                        

    private void saveprofileActionPerformed(java.awt.event.ActionEvent evt) {                                            
        //TODO add your handling code here:
        splash splash = new splash();
        String filePath = "uid.txt";
        File file = new File(filePath);
        String filePath1 = "remember.txt";
        File file1 = new File(filePath1);
        home home = (home) SwingUtilities.getWindowAncestor(profile_dialog.this);

        if (file.exists()) {
            boolean deleted = file.delete();
            if (deleted) {
                if (file1.exists()) {
                    file1.delete();
                }
                splash.setVisible(true);
                home.setVisible(false);
                GlassPanePopup.closePopupLast();
                home.dispose();
            }
        } else {
            splash.setVisible(true);
            home.setVisible(false);
            GlassPanePopup.closePopupLast();
            home.dispose();
        }
        if (file1.exists()) {

        } else {
            file.delete();
            splash.setVisible(true);
            setVisible(false);
            GlassPanePopup.closePopupLast();
            home.dispose();
        }
    }                                           

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        //GlassPanePopup.closePopupLast();
    }                                      


    // Variables declaration - do not modify                     
    private libratech.design.MyButtonborder cancel;
    private javax.swing.JLabel savechangeslabel;
    private libratech.design.MyButtonborderless saveprofile;
    private javax.swing.JTextPane txt;
    // End of variables declaration                   
    public void initFont() {
        savechangeslabel.setFont(new Font("Poppins Regular", Font.BOLD, 20));
        txt.setFont(new Font("Poppins Regular", Font.PLAIN, 16));
        saveprofile.setFont(new Font("Poppins Regular", Font.BOLD, 12));
        cancel.setFont(new Font("Poppins Regular", Font.BOLD, 12));
    }
}
