/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package libratech;

import libratech.models.fontInit;
import com.formdev.flatlaf.FlatLightLaf;
import libratech.util.firebaseInit;
import javax.swing.UIManager;
import libratech.auth.splash;


public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());

        FlatLightLaf.install();
        FlatLightLaf.setup();
        new firebaseInit().initFirebase();
        new fontInit().initialize();

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }

        //ImageIcon logo = new ImageIcon(getClass().getClassLoader().getResources("resources1/logo.png"));
        new splash().setVisible(true);

    }



}
