/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package libratech.design;

import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
/**
 *
 * @author Admin
 */
public class Dates extends javax.swing.JPanel {
    
    private Event event;
    private final int MONTH;
    private final int YEAR;
    private final int DAY;
    private int m;
    private int y;
    private int selectDay = 0;
    private int startDate;
    private int max_of_month;

    /**
     * Creates new form Dates
     */
    public Dates() {
        initComponents();
        setFontForAllLabels();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        String toDay = df.format(date);
        DAY = Integer.valueOf(toDay.split("-")[0]);
        MONTH = Integer.valueOf(toDay.split("-")[1]);
        YEAR = Integer.valueOf(toDay.split("-")[2]);
        
    }
     public void showDate(int month, int year, SelectedDate select) {
        m = month;
        y = year;
        // selectDay = 0;
        Calendar cd = Calendar.getInstance();
        cd.set(year, month - 1, 1);
        int start = cd.get(Calendar.DAY_OF_WEEK);
        max_of_month = cd.getActualMaximum(Calendar.DAY_OF_MONTH);
        if (start == 1) {
            start += 7;
        }
        clear();
        start += 5;
        startDate = start;
        for (int i = 1; i <= max_of_month; i++) {
            Button cmd = (Button) getComponent(start);
            cmd.setColorSelected(getForeground());
            cmd.setText(i + "");
            if (i == DAY && month == MONTH && year == YEAR) {
                cmd.setBackground(new Color(224, 214, 229));
            } else {
                cmd.setBackground(Color.WHITE);
            }
            if (i == select.getDay() && month == select.getMonth() && year == select.getYear()) {
                cmd.setBackground(getForeground());
                cmd.setForeground(new Color(255, 255, 255));
            }
            start++;
        }
    }

    private void clear() {
        for (int i = 7; i < getComponentCount(); i++) {
            ((JButton) getComponent(i)).setText("");
        }
    }

    public void clearSelected() {
        for (int i = 7; i < getComponentCount(); i++) {
            JButton cmd = (JButton) getComponent(i);
            if (MONTH == m && y == YEAR && !cmd.getText().equals("") && Integer.valueOf(cmd.getText()) == DAY) {
                cmd.setBackground(new Color(224, 214, 229));
                cmd.setForeground(new java.awt.Color(75, 75, 75));
            } else {
                cmd.setBackground(Color.WHITE);
                cmd.setForeground(new java.awt.Color(75, 75, 75));
            }
        }
        selectDay = 0;
    }

    private void addEvent() {
        for (int i = 7; i < getComponentCount(); i++) {
            ((Button) getComponent(i)).setEvent(event);
        }
    }

    public void setSelected(int index) {
        selectDay = index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonmo = new libratech.design.Button();
        buttontue = new libratech.design.Button();
        buttonwed = new libratech.design.Button();
        buttonthu = new libratech.design.Button();
        buttonfri = new libratech.design.Button();
        buttonsat = new libratech.design.Button();
        buttonsun = new libratech.design.Button();
        button1 = new libratech.design.Button();
        button2 = new libratech.design.Button();
        button3 = new libratech.design.Button();
        button4 = new libratech.design.Button();
        button5 = new libratech.design.Button();
        button6 = new libratech.design.Button();
        button7 = new libratech.design.Button();
        button8 = new libratech.design.Button();
        button9 = new libratech.design.Button();
        button10 = new libratech.design.Button();
        button11 = new libratech.design.Button();
        button12 = new libratech.design.Button();
        button13 = new libratech.design.Button();
        button14 = new libratech.design.Button();
        button15 = new libratech.design.Button();
        button16 = new libratech.design.Button();
        button17 = new libratech.design.Button();
        button18 = new libratech.design.Button();
        button19 = new libratech.design.Button();
        button20 = new libratech.design.Button();
        button21 = new libratech.design.Button();
        button22 = new libratech.design.Button();
        button23 = new libratech.design.Button();
        button24 = new libratech.design.Button();
        button25 = new libratech.design.Button();
        button26 = new libratech.design.Button();
        button27 = new libratech.design.Button();
        button28 = new libratech.design.Button();
        button29 = new libratech.design.Button();
        button30 = new libratech.design.Button();
        button31 = new libratech.design.Button();
        button32 = new libratech.design.Button();
        button33 = new libratech.design.Button();
        button34 = new libratech.design.Button();
        button35 = new libratech.design.Button();
        button36 = new libratech.design.Button();
        button37 = new libratech.design.Button();
        button38 = new libratech.design.Button();
        button39 = new libratech.design.Button();
        button40 = new libratech.design.Button();
        button41 = new libratech.design.Button();
        button42 = new libratech.design.Button();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(7, 7));

        buttonmo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        buttonmo.setForeground(new java.awt.Color(118, 118, 118));
        buttonmo.setText("Monday");
        add(buttonmo);

        buttontue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        buttontue.setForeground(new java.awt.Color(118, 118, 118));
        buttontue.setText("Tuesday");
        add(buttontue);

        buttonwed.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        buttonwed.setForeground(new java.awt.Color(118, 118, 118));
        buttonwed.setText("Wednesday");
        add(buttonwed);

        buttonthu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        buttonthu.setForeground(new java.awt.Color(118, 118, 118));
        buttonthu.setText("Thursday");
        add(buttonthu);

        buttonfri.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        buttonfri.setForeground(new java.awt.Color(118, 118, 118));
        buttonfri.setText("Friday");
        add(buttonfri);

        buttonsat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        buttonsat.setForeground(new java.awt.Color(118, 118, 118));
        buttonsat.setText("Saturday");
        add(buttonsat);

        buttonsun.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        buttonsun.setForeground(new java.awt.Color(4, 28, 52));
        buttonsun.setText("Sunday");
        add(buttonsun);

        button1.setBackground(new java.awt.Color(250, 250, 250));
        button1.setForeground(new java.awt.Color(75, 75, 75));
        button1.setName("day"); // NOI18N
        add(button1);

        button2.setBackground(new java.awt.Color(250, 250, 250));
        button2.setForeground(new java.awt.Color(75, 75, 75));
        button2.setName("day"); // NOI18N
        add(button2);

        button3.setBackground(new java.awt.Color(250, 250, 250));
        button3.setForeground(new java.awt.Color(75, 75, 75));
        button3.setText("1");
        button3.setName("day"); // NOI18N
        add(button3);

        button4.setBackground(new java.awt.Color(250, 250, 250));
        button4.setForeground(new java.awt.Color(75, 75, 75));
        button4.setText("2");
        button4.setName("day"); // NOI18N
        add(button4);

        button5.setBackground(new java.awt.Color(250, 250, 250));
        button5.setForeground(new java.awt.Color(75, 75, 75));
        button5.setText("3");
        button5.setName("day"); // NOI18N
        add(button5);

        button6.setBackground(new java.awt.Color(250, 250, 250));
        button6.setForeground(new java.awt.Color(75, 75, 75));
        button6.setText("4");
        button6.setName("day"); // NOI18N
        add(button6);

        button7.setBackground(new java.awt.Color(250, 250, 250));
        button7.setForeground(new java.awt.Color(75, 75, 75));
        button7.setText("5");
        button7.setName("day"); // NOI18N
        add(button7);

        button8.setBackground(new java.awt.Color(250, 250, 250));
        button8.setForeground(new java.awt.Color(75, 75, 75));
        button8.setText("6");
        button8.setName("day"); // NOI18N
        add(button8);

        button9.setBackground(new java.awt.Color(250, 250, 250));
        button9.setForeground(new java.awt.Color(75, 75, 75));
        button9.setText("7");
        button9.setName("day"); // NOI18N
        add(button9);

        button10.setBackground(new java.awt.Color(250, 250, 250));
        button10.setForeground(new java.awt.Color(75, 75, 75));
        button10.setText("8");
        button10.setName("day"); // NOI18N
        add(button10);

        button11.setBackground(new java.awt.Color(250, 250, 250));
        button11.setForeground(new java.awt.Color(75, 75, 75));
        button11.setText("9");
        button11.setName("day"); // NOI18N
        add(button11);

        button12.setBackground(new java.awt.Color(250, 250, 250));
        button12.setForeground(new java.awt.Color(75, 75, 75));
        button12.setText("10");
        button12.setName("day"); // NOI18N
        add(button12);

        button13.setBackground(new java.awt.Color(250, 250, 250));
        button13.setForeground(new java.awt.Color(75, 75, 75));
        button13.setText("11");
        button13.setName("day"); // NOI18N
        add(button13);

        button14.setBackground(new java.awt.Color(250, 250, 250));
        button14.setForeground(new java.awt.Color(75, 75, 75));
        button14.setText("12");
        button14.setName("day"); // NOI18N
        add(button14);

        button15.setBackground(new java.awt.Color(250, 250, 250));
        button15.setForeground(new java.awt.Color(75, 75, 75));
        button15.setText("13");
        button15.setName("day"); // NOI18N
        add(button15);

        button16.setBackground(new java.awt.Color(250, 250, 250));
        button16.setForeground(new java.awt.Color(75, 75, 75));
        button16.setText("14");
        button16.setName("day"); // NOI18N
        add(button16);

        button17.setBackground(new java.awt.Color(250, 250, 250));
        button17.setForeground(new java.awt.Color(75, 75, 75));
        button17.setText("15");
        button17.setName("day"); // NOI18N
        add(button17);

        button18.setBackground(new java.awt.Color(250, 250, 250));
        button18.setForeground(new java.awt.Color(75, 75, 75));
        button18.setText("16");
        button18.setName("day"); // NOI18N
        add(button18);

        button19.setBackground(new java.awt.Color(250, 250, 250));
        button19.setForeground(new java.awt.Color(75, 75, 75));
        button19.setText("17");
        button19.setName("day"); // NOI18N
        add(button19);

        button20.setBackground(new java.awt.Color(250, 250, 250));
        button20.setForeground(new java.awt.Color(75, 75, 75));
        button20.setText("18");
        button20.setName("day"); // NOI18N
        add(button20);

        button21.setBackground(new java.awt.Color(250, 250, 250));
        button21.setForeground(new java.awt.Color(75, 75, 75));
        button21.setText("19");
        button21.setName("day"); // NOI18N
        add(button21);

        button22.setBackground(new java.awt.Color(250, 250, 250));
        button22.setForeground(new java.awt.Color(75, 75, 75));
        button22.setText("20");
        button22.setName("day"); // NOI18N
        add(button22);

        button23.setBackground(new java.awt.Color(250, 250, 250));
        button23.setForeground(new java.awt.Color(75, 75, 75));
        button23.setText("21");
        button23.setName("day"); // NOI18N
        add(button23);

        button24.setBackground(new java.awt.Color(250, 250, 250));
        button24.setForeground(new java.awt.Color(75, 75, 75));
        button24.setText("22");
        button24.setName("day"); // NOI18N
        add(button24);

        button25.setBackground(new java.awt.Color(250, 250, 250));
        button25.setForeground(new java.awt.Color(75, 75, 75));
        button25.setText("23");
        button25.setName("day"); // NOI18N
        add(button25);

        button26.setBackground(new java.awt.Color(250, 250, 250));
        button26.setForeground(new java.awt.Color(75, 75, 75));
        button26.setText("24");
        button26.setName("day"); // NOI18N
        add(button26);

        button27.setBackground(new java.awt.Color(250, 250, 250));
        button27.setForeground(new java.awt.Color(75, 75, 75));
        button27.setText("25");
        button27.setName("day"); // NOI18N
        add(button27);

        button28.setBackground(new java.awt.Color(250, 250, 250));
        button28.setForeground(new java.awt.Color(75, 75, 75));
        button28.setText("26");
        button28.setName("day"); // NOI18N
        add(button28);

        button29.setBackground(new java.awt.Color(250, 250, 250));
        button29.setForeground(new java.awt.Color(75, 75, 75));
        button29.setText("27");
        button29.setName("day"); // NOI18N
        add(button29);

        button30.setBackground(new java.awt.Color(250, 250, 250));
        button30.setForeground(new java.awt.Color(75, 75, 75));
        button30.setText("28");
        button30.setName("day"); // NOI18N
        add(button30);

        button31.setBackground(new java.awt.Color(250, 250, 250));
        button31.setForeground(new java.awt.Color(75, 75, 75));
        button31.setText("29");
        button31.setName("day"); // NOI18N
        add(button31);

        button32.setBackground(new java.awt.Color(250, 250, 250));
        button32.setForeground(new java.awt.Color(75, 75, 75));
        button32.setText("30");
        button32.setName("day"); // NOI18N
        add(button32);

        button33.setBackground(new java.awt.Color(250, 250, 250));
        button33.setForeground(new java.awt.Color(75, 75, 75));
        button33.setText("31");
        button33.setName("day"); // NOI18N
        add(button33);

        button34.setBackground(new java.awt.Color(250, 250, 250));
        button34.setName("day"); // NOI18N
        add(button34);

        button35.setBackground(new java.awt.Color(250, 250, 250));
        button35.setName("day"); // NOI18N
        add(button35);

        button36.setBackground(new java.awt.Color(250, 250, 250));
        button36.setName("day"); // NOI18N
        add(button36);

        button37.setBackground(new java.awt.Color(250, 250, 250));
        button37.setName("day"); // NOI18N
        add(button37);

        button38.setBackground(new java.awt.Color(250, 250, 250));
        button38.setName("day"); // NOI18N
        add(button38);

        button39.setBackground(new java.awt.Color(250, 250, 250));
        button39.setName("day"); // NOI18N
        add(button39);

        button40.setBackground(new java.awt.Color(250, 250, 250));
        button40.setName("day"); // NOI18N
        add(button40);

        button41.setBackground(new java.awt.Color(250, 250, 250));
        button41.setName("day"); // NOI18N
        add(button41);

        button42.setBackground(new java.awt.Color(250, 250, 250));
        button42.setName("day"); // NOI18N
        add(button42);
    }// </editor-fold>//GEN-END:initComponents
    public Event getEvent() {
        return event;
    }

    public void setEvent(Event event) {
        this.event = event;
        addEvent();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private libratech.design.Button button1;
    private libratech.design.Button button10;
    private libratech.design.Button button11;
    private libratech.design.Button button12;
    private libratech.design.Button button13;
    private libratech.design.Button button14;
    private libratech.design.Button button15;
    private libratech.design.Button button16;
    private libratech.design.Button button17;
    private libratech.design.Button button18;
    private libratech.design.Button button19;
    private libratech.design.Button button2;
    private libratech.design.Button button20;
    private libratech.design.Button button21;
    private libratech.design.Button button22;
    private libratech.design.Button button23;
    private libratech.design.Button button24;
    private libratech.design.Button button25;
    private libratech.design.Button button26;
    private libratech.design.Button button27;
    private libratech.design.Button button28;
    private libratech.design.Button button29;
    private libratech.design.Button button3;
    private libratech.design.Button button30;
    private libratech.design.Button button31;
    private libratech.design.Button button32;
    private libratech.design.Button button33;
    private libratech.design.Button button34;
    private libratech.design.Button button35;
    private libratech.design.Button button36;
    private libratech.design.Button button37;
    private libratech.design.Button button38;
    private libratech.design.Button button39;
    private libratech.design.Button button4;
    private libratech.design.Button button40;
    private libratech.design.Button button41;
    private libratech.design.Button button42;
    private libratech.design.Button button5;
    private libratech.design.Button button6;
    private libratech.design.Button button7;
    private libratech.design.Button button8;
    private libratech.design.Button button9;
    private libratech.design.Button buttonfri;
    private libratech.design.Button buttonmo;
    private libratech.design.Button buttonsat;
    private libratech.design.Button buttonsun;
    private libratech.design.Button buttonthu;
    private libratech.design.Button buttontue;
    private libratech.design.Button buttonwed;
    // End of variables declaration//GEN-END:variables
     public void next() {
        if (selectDay == max_of_month) {
            selectDay = 0;
        }
        JButton cmd = (JButton) getComponent(startDate - 1 + selectDay + 1);
        String n = cmd.getText();
        if (!n.equals("") && Integer.valueOf(n) <= max_of_month) {
            selectDay++;
            event.execute(null, selectDay);
            cmd.setBackground(new Color(206, 110, 245));
        }
    }

    public void back() {
        if (selectDay <= 1) {
            selectDay = max_of_month + 1;
        }
        JButton cmd = (JButton) getComponent(startDate - 1 + selectDay - 1);
        String n = cmd.getText();
        if (!n.equals("") && cmd.getName() != null) {
            selectDay--;
            event.execute(null, selectDay);
            cmd.setBackground(new Color(206, 110, 245));
        }
    }

    public void up() {
        JButton cmd = (JButton) getComponent(startDate - 1 + selectDay - 7);
        String n = cmd.getText();
        if (!n.equals("") && cmd.getName() != null) {
            selectDay -= 7;
            event.execute(null, selectDay);
            cmd.setBackground(new Color(206, 110, 245));
        }
    }

    public void down() {
        if (getComponents().length > startDate - 1 + selectDay + 7) {
            JButton cmd = (JButton) getComponent(startDate - 1 + selectDay + 7);
            String n = cmd.getText();
            if (!n.equals("") && cmd.getName() != null) {
                selectDay += 7;
                event.execute(null, selectDay);
                cmd.setBackground(new Color(206, 110, 245));
            }
        }
    }
    private void setFontForAllLabels() {
        for (int i = 0; i < this.getComponentCount(); i++) {
            if (this.getComponent(i) instanceof JButton label) {
                label.setFont(new Font("Poppins Regular", Font.PLAIN, 12));
                label.setBackground(new Color(255,255,255));
            }
        }
    }
}
