/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package libratech.design;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;

/**
 *
 * @author Admin
 */
public class Months extends javax.swing.JPanel {

    /**
     * Creates new form Months
     */
    private Event event;
    private int m;
    
    public Months() {
        initComponents();
        setFontForAllLabels();
    }
    private void addEvent() {
        for (int i = 0; i < getComponentCount(); i++) {
            ((Button) getComponent(i)).setEvent(event);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new libratech.design.Button();
        button2 = new libratech.design.Button();
        button3 = new libratech.design.Button();
        button4 = new libratech.design.Button();
        button5 = new libratech.design.Button();
        button6 = new libratech.design.Button();
        button7 = new libratech.design.Button();
        button8 = new libratech.design.Button();
        button9 = new libratech.design.Button();
        button10 = new libratech.design.Button();
        button11 = new libratech.design.Button();
        button12 = new libratech.design.Button();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(4, 4));

        button1.setForeground(new java.awt.Color(75, 75, 75));
        button1.setText("January");
        button1.setName("1"); // NOI18N
        button1.setOpaque(true);
        add(button1);

        button2.setForeground(new java.awt.Color(75, 75, 75));
        button2.setText("February");
        button2.setName("2"); // NOI18N
        button2.setOpaque(true);
        add(button2);

        button3.setForeground(new java.awt.Color(75, 75, 75));
        button3.setText("March");
        button3.setName("3"); // NOI18N
        button3.setOpaque(true);
        add(button3);

        button4.setForeground(new java.awt.Color(75, 75, 75));
        button4.setText("April");
        button4.setName("4"); // NOI18N
        button4.setOpaque(true);
        add(button4);

        button5.setForeground(new java.awt.Color(75, 75, 75));
        button5.setText("May");
        button5.setName("5"); // NOI18N
        button5.setOpaque(true);
        add(button5);

        button6.setForeground(new java.awt.Color(75, 75, 75));
        button6.setText("June");
        button6.setName("6"); // NOI18N
        button6.setOpaque(true);
        add(button6);

        button7.setForeground(new java.awt.Color(75, 75, 75));
        button7.setText("July");
        button7.setName("7"); // NOI18N
        button7.setOpaque(true);
        add(button7);

        button8.setForeground(new java.awt.Color(75, 75, 75));
        button8.setText("August");
        button8.setName("8"); // NOI18N
        button8.setOpaque(true);
        add(button8);

        button9.setForeground(new java.awt.Color(75, 75, 75));
        button9.setText("September");
        button9.setName("9"); // NOI18N
        button9.setOpaque(true);
        add(button9);

        button10.setForeground(new java.awt.Color(75, 75, 75));
        button10.setText("October");
        button10.setName("10"); // NOI18N
        button10.setOpaque(true);
        add(button10);

        button11.setForeground(new java.awt.Color(75, 75, 75));
        button11.setText("November");
        button11.setName("11"); // NOI18N
        button11.setOpaque(true);
        add(button11);

        button12.setForeground(new java.awt.Color(75, 75, 75));
        button12.setText("December");
        button12.setName("12"); // NOI18N
        button12.setOpaque(true);
        add(button12);
    }// </editor-fold>//GEN-END:initComponents
    
    
    public Event getEvent() {
        return event;
    }

    public void setEvent(Event event) {
        this.event = event;
        addEvent();
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private libratech.design.Button button1;
    private libratech.design.Button button10;
    private libratech.design.Button button11;
    private libratech.design.Button button12;
    private libratech.design.Button button2;
    private libratech.design.Button button3;
    private libratech.design.Button button4;
    private libratech.design.Button button5;
    private libratech.design.Button button6;
    private libratech.design.Button button7;
    private libratech.design.Button button8;
    private libratech.design.Button button9;
    // End of variables declaration//GEN-END:variables
     private void setFontForAllLabels() {
        for (int i = 0; i < this.getComponentCount(); i++) {
            if (this.getComponent(i) instanceof JButton label) {
                label.setFont(new Font("Poppins Regular", Font.PLAIN, 12));
                label.setBackground(new Color(255,255,255));
            }
        }
     }
}
