/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package libratech.design;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
/**
 *
 * @author Admin
 */
public class Years extends javax.swing.JPanel {
    
    private Event event;
    private int startYear;
    
    /**
     * Creates new form Years
     */
   
    public Years() {
        initComponents();
        setFontForAllLabels();
    }
     public int showYear(int year) {
        year = calculateYear(year);
        for (int i = 0; i < getComponentCount(); i++) {
            JButton cmd = (JButton) getComponent(i);
            cmd.setText(year + "");
            year++;
        }
        return startYear;
    }

    private int calculateYear(int year) {
        year -= year % 10;
        startYear = year;
        return year;
    }

    private void addEvent() {
        for (int i = 0; i < getComponentCount(); i++) {
            ((Button) getComponent(i)).setEvent(event);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button26 = new libratech.design.Button();
        button1 = new libratech.design.Button();
        button2 = new libratech.design.Button();
        button3 = new libratech.design.Button();
        button4 = new libratech.design.Button();
        button5 = new libratech.design.Button();
        button6 = new libratech.design.Button();
        button7 = new libratech.design.Button();
        button8 = new libratech.design.Button();
        button9 = new libratech.design.Button();
        button10 = new libratech.design.Button();
        button11 = new libratech.design.Button();
        button12 = new libratech.design.Button();
        button13 = new libratech.design.Button();
        button14 = new libratech.design.Button();
        button15 = new libratech.design.Button();
        button16 = new libratech.design.Button();
        button17 = new libratech.design.Button();
        button18 = new libratech.design.Button();
        button19 = new libratech.design.Button();
        button20 = new libratech.design.Button();

        button26.setText("button26");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(5, 4));

        button1.setBackground(new java.awt.Color(250, 250, 250));
        button1.setForeground(new java.awt.Color(75, 75, 75));
        button1.setText("2005");
        button1.setName("year"); // NOI18N
        button1.setOpaque(true);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);

        button2.setBackground(new java.awt.Color(250, 250, 250));
        button2.setForeground(new java.awt.Color(75, 75, 75));
        button2.setText("2006");
        button2.setName("year"); // NOI18N
        button2.setOpaque(true);
        add(button2);

        button3.setBackground(new java.awt.Color(250, 250, 250));
        button3.setForeground(new java.awt.Color(75, 75, 75));
        button3.setText("2007");
        button3.setName("year"); // NOI18N
        button3.setOpaque(true);
        add(button3);

        button4.setBackground(new java.awt.Color(250, 250, 250));
        button4.setForeground(new java.awt.Color(75, 75, 75));
        button4.setText("2008");
        button4.setName("year"); // NOI18N
        button4.setOpaque(true);
        add(button4);

        button5.setBackground(new java.awt.Color(250, 250, 250));
        button5.setForeground(new java.awt.Color(75, 75, 75));
        button5.setText("2009");
        button5.setName("year"); // NOI18N
        button5.setOpaque(true);
        add(button5);

        button6.setBackground(new java.awt.Color(250, 250, 250));
        button6.setForeground(new java.awt.Color(75, 75, 75));
        button6.setText("2010");
        button6.setName("year"); // NOI18N
        button6.setOpaque(true);
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        add(button6);

        button7.setBackground(new java.awt.Color(250, 250, 250));
        button7.setForeground(new java.awt.Color(75, 75, 75));
        button7.setText("2011");
        button7.setName("year"); // NOI18N
        button7.setOpaque(true);
        add(button7);

        button8.setBackground(new java.awt.Color(250, 250, 250));
        button8.setForeground(new java.awt.Color(75, 75, 75));
        button8.setText("2012");
        button8.setName("year"); // NOI18N
        button8.setOpaque(true);
        add(button8);

        button9.setBackground(new java.awt.Color(250, 250, 250));
        button9.setForeground(new java.awt.Color(75, 75, 75));
        button9.setText("2013");
        button9.setName("year"); // NOI18N
        button9.setOpaque(true);
        add(button9);

        button10.setBackground(new java.awt.Color(250, 250, 250));
        button10.setForeground(new java.awt.Color(75, 75, 75));
        button10.setText("2014");
        button10.setName("year"); // NOI18N
        button10.setOpaque(true);
        add(button10);

        button11.setBackground(new java.awt.Color(250, 250, 250));
        button11.setForeground(new java.awt.Color(75, 75, 75));
        button11.setText("2015");
        button11.setName("year"); // NOI18N
        button11.setOpaque(true);
        add(button11);

        button12.setBackground(new java.awt.Color(250, 250, 250));
        button12.setForeground(new java.awt.Color(75, 75, 75));
        button12.setText("2016");
        button12.setName("year"); // NOI18N
        button12.setOpaque(true);
        add(button12);

        button13.setBackground(new java.awt.Color(250, 250, 250));
        button13.setForeground(new java.awt.Color(75, 75, 75));
        button13.setText("2017");
        button13.setName("year"); // NOI18N
        button13.setOpaque(true);
        add(button13);

        button14.setBackground(new java.awt.Color(250, 250, 250));
        button14.setForeground(new java.awt.Color(75, 75, 75));
        button14.setText("2018");
        button14.setName("year"); // NOI18N
        button14.setOpaque(true);
        add(button14);

        button15.setBackground(new java.awt.Color(250, 250, 250));
        button15.setForeground(new java.awt.Color(75, 75, 75));
        button15.setText("2019");
        button15.setName("year"); // NOI18N
        button15.setOpaque(true);
        add(button15);

        button16.setBackground(new java.awt.Color(250, 250, 250));
        button16.setForeground(new java.awt.Color(75, 75, 75));
        button16.setText("2020");
        button16.setName("year"); // NOI18N
        button16.setOpaque(true);
        add(button16);

        button17.setBackground(new java.awt.Color(250, 250, 250));
        button17.setForeground(new java.awt.Color(75, 75, 75));
        button17.setText("2021");
        button17.setName("year"); // NOI18N
        button17.setOpaque(true);
        add(button17);

        button18.setBackground(new java.awt.Color(250, 250, 250));
        button18.setForeground(new java.awt.Color(75, 75, 75));
        button18.setText("2022");
        button18.setName("year"); // NOI18N
        button18.setOpaque(true);
        add(button18);

        button19.setBackground(new java.awt.Color(250, 250, 250));
        button19.setForeground(new java.awt.Color(75, 75, 75));
        button19.setText("2023");
        button19.setName("year"); // NOI18N
        button19.setOpaque(true);
        add(button19);

        button20.setBackground(new java.awt.Color(250, 250, 250));
        button20.setForeground(new java.awt.Color(75, 75, 75));
        button20.setText("2024");
        button20.setName("year"); // NOI18N
        button20.setOpaque(true);
        add(button20);
    }// </editor-fold>//GEN-END:initComponents

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button6ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed
    public Event getEvent() {
        return event;
    }

    public void setEvent(Event event) {
        this.event = event;
        addEvent();
    }

    public int next(int year) {
        showYear(year + 20);
        return startYear;
    }

    public int back(int year) {
        showYear(year - 20);
        return startYear;
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private libratech.design.Button button1;
    private libratech.design.Button button10;
    private libratech.design.Button button11;
    private libratech.design.Button button12;
    private libratech.design.Button button13;
    private libratech.design.Button button14;
    private libratech.design.Button button15;
    private libratech.design.Button button16;
    private libratech.design.Button button17;
    private libratech.design.Button button18;
    private libratech.design.Button button19;
    private libratech.design.Button button2;
    private libratech.design.Button button20;
    private libratech.design.Button button26;
    private libratech.design.Button button3;
    private libratech.design.Button button4;
    private libratech.design.Button button5;
    private libratech.design.Button button6;
    private libratech.design.Button button7;
    private libratech.design.Button button8;
    private libratech.design.Button button9;
    // End of variables declaration//GEN-END:variables
    private void setFontForAllLabels() {
        for (int i = 0; i < this.getComponentCount(); i++) {
            if (this.getComponent(i) instanceof JButton label) {
                label.setFont(new Font("Poppins Regular", Font.PLAIN, 12));
                label.setBackground(new Color(255,255,255));
            }
        }
    }
}
