package libratech.models;


public class ClassificationInfo {
    
    public ClassificationInfo() {
        
    }
    
    public String[] getClassification() {
        
        String[] Classification = {
            
            "Computer Science, Information and General Works",
            "Bibliographies",
            "Library & Information Sciences",
            "Encyclopedia & books of facts",
            " ",
            "Magazines, Journals & Serials",
            "Associations, Organizations & Museums",
            "News Media, Journalism & Publishing",
            "Quotations",
            "Manuscripts & Rare Books",
            
            "Philosophy and Psychology",
            "Metaphysics",
            "Epistemology",
            "Parapsychology & Occultism",
            "Philosophical Schools of Thought",
            "Psychology",
            "Logic",
            "Ethics",
            "Ancient, Medieval & Eastern Philosophy",
            "Modern Western Philosophy",
            
            "Religion",
            "Philosophy & Theory of Religion",
            "The Bible",
            "Christianity & Christian Theology",
            "Christian Practice & Observance",
            "Christian Pastoral Practice & Religious Orders",
            "Christian Organizatinoos, Social work & Worship",
            "History of Christianity",
            "Christian Denomination",
            "Other Religions",
            
            "Social Sciences, Sociology & Anthropology",
            "Statistics",
            "Political Science",
            "Economics",
            "Law",
            "Public Administration & Military Sciences",
            "Social Problems & Social Services",
            "Education",
            "Commerce, Communications & Transportation",
            "Customs, Etiquette & Folklore",
            
            "Language",
            "Linguistics",
            "English & Old English Languages",
            "German & Related Languages",
            "French & Related Languages",
            "Italian, Romanian & Related Languages",
            "Spanish & Portuguese Languages",
            "Latin & Italic Languages",
            "Classical & Modern Greek Languages",
            "Other Languages",
            
            "Science",
            "Mathematics",
            "Astronomy",
            "Physics",
            "Chemistry",
            "Earth Sciences & Geology",
            "Fossils & Prehistoric Life",
            "Life Sciences; Biology",
            "Plants (Botany)",
            "Animals (Zoology)",
            
            "Technology",
            "Medicine & Health",
            "Engineering",
            "Agriculture",
            "Home & Family Management",
            "Management & Public Relations",
            "Chemical Engineering",
            "Manufacturing",
            "Manufacturing for Specific Uses",
            "Building & Construction",
            
            "Arts and Recreation",
            "Landscaping & Are Planning",
            "Architecture",
            "Sculpture, Ceramincs & Metalwork",
            "Drawing & Decorative Arts",
            "Painting",
            "Graphic Arts",
            "Photography & Computer Art",
            "Music",
            "Sports, Games & Entertainment",
            
            "Literature",
            "Literature, Rhetoric & Criticism",
            "Americn Literature in English",
            "English & Old English Literatures",
            "German & Related Literatures",
            "French & Related Literatures",
            "Italian, Romanian & Related Literatures",
            "Spanish & Portugues Literatures",
            "Latin & Italic Litetratures",
            "Classical * Modern Greek Literatures",
            "Other Literatures",
            
            "History and Geography",
            "Geography and Travel",
            "Biography & Genealogy",
            "History of Ancient World",
            "History of Europe",
            "History of Asia",
            "Histry of Africa",
            "History of North America",
            "History of South America",
            "History of Other Areas"
        };
        return Classification;
    }
    
    
    public String[] getDeweyNo() {
        
        String[] DeweyNumber = 
        {
            "000",
            "010",
            "020",
            "030",
            "040",
            "050",
            "060",
            "070",
            "080",
            "090",
            
            "100",
            "110",
            "120",
            "130",
            "140",
            "150",
            "160",
            "170",
            "180",
            "190",
            
            "200",
            "210",
            "220",
            "230",
            "240",
            "250",
            "260",
            "270",
            "280",
            "290",
            
            "300",
            "310",
            "320",
            "330",
            "340",
            "350",
            "360",
            "370",
            "380",
            "390",
            
            "400",
            "410",
            "420",
            "430",
            "440",
            "450",
            "460",
            "470",
            "480",
            "490",
            
            "500",
            "510",
            "520",
            "530",
            "540",
            "550",
            "560",
            "570",
            "580",
            "590",
            
            "600",
            "610",
            "620",
            "630",
            "640",
            "650",
            "660",
            "670",
            "680",
            "690",
            
            "700",
            "710",
            "720",
            "730",
            "740",
            "750",
            "760",
            "770",
            "780",
            "790",
            
            "800",
            "810",
            "820",
            "830",
            "840",
            "850",
            "860",
            "870",
            "880",
            "890",
            "900",
            
            "910",
            "920",
            "930",
            "940",
            "950",
            "960",
            "970",
            "980",
            "990"
        };
        
        return DeweyNumber;
    }
}